
version: '3.8'
services:
  rag-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - VECTOR_DB_URL=http://qdrant:6333
      - LLM_PROVIDER=openai
    depends_on:
      - qdrant
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
